Umstellung auf GITHUB_TOKEN für Deployment
- Verwendung des automatischen Tokens von GitHub
  für das Deployment
- Hugo generiert die Seite jetzt in das Verzeichnis
  `generated-site`. Der Name macht leichter deutlich,
  dass es sich um ein temporäres Verzeichnis handelt
  und was sich in diesem befindet
- GitHub Actions Workflow ausgebaut, so dass dieser
  die Existenz des CNAME-Files überprüft sowie
  die korrekte Konfiguration der beteiligten
  Nameserver

diff --git a/.github/workflows/gh-pages-deployment.yml b/.github/workflows/gh-pages-deployment.yml
--- a/.github/workflows/gh-pages-deployment.yml
+++ b/.github/workflows/gh-pages-deployment.yml
@@ -1,9 +1,14 @@
 name: GitHub Pages
 
 on:
+  workflow_dispatch:
   push:
     branches:
       - main
+
+# Controls the permissions for the GitHub token
+permissions:
+  contents: write
 
 jobs:
   build-deploy:
@@ -21,9 +26,61 @@ jobs:
       - name: Build
         run: hugo
 
+      - name: Check Bash Version
+        shell: bash
+        run:  bash --version
+
+      - name: Check CNAME file
+        shell: bash
+        run: |
+          if [ ! -f generated-site/CNAME ]; then
+            echo "::error file=CNAME,line=,title=CNAME file is missing::CNAME file not found in site generated by Hugo"
+            echo "::group::Contents of directory generated-site/"
+            ls -la generated-site/ || echo "Directory generated-site does not exist"
+            echo "::endgroup::"
+            exit 1
+          fi
+      - name: Check DNS Configuration
+        run: |          
+          function check() {
+            local ns=$1
+            local type=$2
+            local -n expected=$3
+          
+            if [ "$ns" = "NIL" ]; then
+              local ACTUAL_IPS=$(dig +short ${type} "jug-berlin-brandenburg.de" | sort)
+            else
+              local ACTUAL_IPS=$(dig ${ns} +short ${type} "jug-berlin-brandenburg.de" | sort)
+            fi
+          
+            echo "::group::Erwartet IP-Adressen von NS" $([[ "$ns" == "NIL" ]] && echo "von GitHub" || echo "$ns")
+            echo "$expected"
+            echo "::endgroup::"
+          
+            echo "::group::Gefundene IP-Adressen in NS" $([[ "$ns" == "NIL" ]] && echo "von GitHub" || echo "$ns")
+            echo "$ACTUAL_IPS"
+            echo "::endgroup::"
+          
+            if [ ! "$ACTUAL_IPS" = "$expected" ]; then
+              echo "::error::🔥IP-Adressen für ${type} Record stimmen nicht überein für NS" $([[ "$ns" == "NIL" ]] && echo "von GitHub" || echo "$ns")
+              exit 1
+            fi          
+          }
+          
+          EXPECTED_A_IPS=$(printf "%s\n" "185.199.108.153" "185.199.109.153" "185.199.110.153" "185.199.111.153" | sort)
+          EXPECTED_AAAA_IPS=$(printf "%s\n" "2606:50c0:8000::153" "2606:50c0:8001::153" "2606:50c0:8002::153" "2606:50c0:8003::153" | sort)
+          
+          for ns in ns1.your-server.de. ns.second-ns.com. ns3.second-ns.de. ; do
+            check @${ns} A EXPECTED_A_IPS 
+            check @${ns} AAAA EXPECTED_AAAA_IPS 
+          done
+                    
+          check "NIL" A EXPECTED_A_IPS 
+          check "NIL" AAAA EXPECTED_AAAA_IPS 
+
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v4
-        env:
-          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
-          PUBLISH_BRANCH: gh-pages
-          PUBLISH_DIR: ./public
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_branch: gh-pages
+          publish_dir: ./generated-site
